<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SolusiSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('solusi')->insert([
            [
                'id_solusi' => 1,
                'id_diagnosa' => 1,
                'solusi_diagnosa' => 'Pertahankan pola penggunaan saat ini.',
                'catatan_pakar' => 'Solusi sudah benar',
                'created_at' => '2025-06-01 10:27:38',
                'updated_at' => '2025-06-01 11:44:15',
                'status_verifikasi' => 'diterima',
            ],
            [
                'id_solusi' => 2,
                'id_diagnosa' => 1,
                'solusi_diagnosa' => 'Tetap sadari waktu online agar tidak bergeser ke penggunaan berlebihan.',
                'catatan_pakar' => null,
                'created_at' => '2025-06-01 10:27:48',
                'updated_at' => '2025-06-01 12:06:31',
                'status_verifikasi' => 'diterima',
            ],
            [
                'id_solusi' => 3,
                'id_diagnosa' => 1,
                'solusi_diagnosa' => 'Gunakan media sosial untuk hal produktif atau edukatif.',
                'catatan_pakar' => null,
                'created_at' => '2025-06-01 10:28:03',
                'updated_at' => '2025-06-01 12:06:36',
                'status_verifikasi' => 'diterima',
            ],
            [
                'id_solusi' => 4,
                'id_diagnosa' => 2,
                'solusi_diagnosa' => 'Tentukan waktu khusus untuk membuka media sosial (misal hanya 30 menit pagi/sore).',
                'catatan_pakar' => 'data solusi sudah sesuai',
                'created_at' => '2025-06-01 10:28:23',
                'updated_at' => '2025-06-01 23:56:08',
                'status_verifikasi' => 'diterima',
            ],
            [
                'id_solusi' => 5,
                'id_diagnosa' => 2,
                'solusi_diagnosa' => 'Matikan notifikasi yang tidak penting.',
                'catatan_pakar' => null,
                'created_at' => '2025-06-01 10:28:34',
                'updated_at' => '2025-06-01 23:56:12',
                'status_verifikasi' => 'diterima',
            ],
            [
                'id_solusi' => 6,
                'id_diagnosa' => 2,
                'solusi_diagnosa' => 'Ganti kebiasaan mengecek media sosial dengan aktivitas lain (baca buku, olahraga ringan).',
                'catatan_pakar' => null,
                'created_at' => '2025-06-01 10:28:48',
                'updated_at' => '2025-06-01 23:56:18',
                'status_verifikasi' => 'diterima',
            ],
            [
                'id_solusi' => 7,
                'id_diagnosa' => 2,
                'solusi_diagnosa' => 'Gunakan fitur “Screen Time” atau “Digital Wellbeing” di ponsel.',
                'catatan_pakar' => null,
                'created_at' => '2025-06-01 10:29:01',
                'updated_at' => '2025-06-01 23:56:26',
                'status_verifikasi' => 'diterima',
            ],
            [
                'id_solusi' => 8,
                'id_diagnosa' => 3,
                'solusi_diagnosa' => 'Buat jurnal harian untuk menyadari kapan dan mengapa kamu membuka media sosial.',
                'catatan_pakar' => null,
                'created_at' => '2025-06-01 10:29:21',
                'updated_at' => '2025-06-01 23:56:32',
                'status_verifikasi' => 'diterima',
            ],
            [
                'id_solusi' => 9,
                'id_diagnosa' => 3,
                'solusi_diagnosa' => 'Latih teknik manajemen stres (seperti pernapasan atau meditasi ringan).',
                'catatan_pakar' => null,
                'created_at' => '2025-06-01 10:29:37',
                'updated_at' => '2025-06-01 23:56:38',
                'status_verifikasi' => 'diterima',
            ],
            [
                'id_solusi' => 10,
                'id_diagnosa' => 3,
                'solusi_diagnosa' => 'Terapkan social media detox ringan (1 hari tanpa medsos per minggu).',
                'catatan_pakar' => null,
                'created_at' => '2025-06-01 10:30:03',
                'updated_at' => '2025-06-01 10:30:03',
                'status_verifikasi' => 'menunggu',
            ],
            [
                'id_solusi' => 11,
                'id_diagnosa' => 3,
                'solusi_diagnosa' => 'Gunakan aplikasi pembatas waktu (seperti Forest, Focus, atau AppBlock).',
                'catatan_pakar' => null,
                'created_at' => '2025-06-01 10:30:17',
                'updated_at' => '2025-06-01 10:30:17',
                'status_verifikasi' => 'menunggu',
            ],
            [
                'id_solusi' => 12,
                'id_diagnosa' => 4,
                'solusi_diagnosa' => 'Konsultasi dengan konselor atau psikolog untuk membahas perilaku digital.',
                'catatan_pakar' => null,
                'created_at' => '2025-06-01 10:30:34',
                'updated_at' => '2025-06-01 23:56:48',
                'status_verifikasi' => 'diterima',
            ],
            [
                'id_solusi' => 13,
                'id_diagnosa' => 4,
                'solusi_diagnosa' => 'Batasi akses dengan menghapus aplikasi dari layar utama atau logout setelah penggunaan.',
                'catatan_pakar' => null,
                'created_at' => '2025-06-01 10:30:51',
                'updated_at' => '2025-06-01 23:56:54',
                'status_verifikasi' => 'diterima',
            ],
            [
                'id_solusi' => 14,
                'id_diagnosa' => 4,
                'solusi_diagnosa' => 'Tetapkan “zona bebas media sosial” seperti kamar tidur, ruang makan, atau waktu keluarga.',
                'catatan_pakar' => null,
                'created_at' => '2025-06-01 10:31:02',
                'updated_at' => '2025-06-01 23:56:58',
                'status_verifikasi' => 'diterima',
            ],
            [
                'id_solusi' => 15,
                'id_diagnosa' => 4,
                'solusi_diagnosa' => 'Minta dukungan teman/keluarga untuk ikut mengingatkan dan mendampingi proses pengurangan.',
                'catatan_pakar' => null,
                'created_at' => '2025-06-01 10:31:16',
                'updated_at' => '2025-06-01 23:57:04',
                'status_verifikasi' => 'diterima',
            ],
            [
                'id_solusi' => 16,
                'id_diagnosa' => 5,
                'solusi_diagnosa' => 'Lakukan terapi perilaku kognitif (CBT) dengan profesional kesehatan mental.',
                'catatan_pakar' => null,
                'created_at' => '2025-06-01 10:31:16',
                'updated_at' => '2025-06-01 23:57:04',
                'status_verifikasi' => 'diterima',
            ],
             [
                'id_solusi' => 17,
                'id_diagnosa' => 5,
                'solusi_diagnosa' => 'Pertimbangkan program rehabilitasi digital atau digital detox camp.',
                'catatan_pakar' => null,
                'created_at' => '2025-06-01 10:31:16',
                'updated_at' => '2025-06-01 23:57:04',
                'status_verifikasi' => 'diterima',
            ],
             [
                'id_solusi' => 18,
                'id_diagnosa' => 5,
                'solusi_diagnosa' => 'Libatkan lingkungan sekitar secara aktif (keluarga, guru, teman dekat).',
                'catatan_pakar' => null,
                'created_at' => '2025-06-01 10:31:16',
                'updated_at' => '2025-06-01 23:57:04',
                'status_verifikasi' => 'diterima',
            ],
             [
                'id_solusi' => 19,
                'id_diagnosa' => 5,
                'solusi_diagnosa' => 'Buat rencana penggunaan teknologi jangka panjang dengan target dan evaluasi rutin.',
                'catatan_pakar' => null,
                'created_at' => '2025-06-01 10:31:16',
                'updated_at' => '2025-06-01 23:57:04',
                'status_verifikasi' => 'diterima',
            ],
        ]);
    }
}
